// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfGg1liqvsfT33cUxxTXyXBH4Npm3UWMY',
    appId: '1:175859677786:web:b9fe640aa0a5d4f8feb663',
    messagingSenderId: '175859677786',
    projectId: 'e-commers-app-38034',
    authDomain: 'e-commers-app-38034.firebaseapp.com',
    storageBucket: 'e-commers-app-38034.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBid_lxd8I0nRjflViwhvb8b6ENjW7oN08',
    appId: '1:175859677786:android:234f076b4bdce00ffeb663',
    messagingSenderId: '175859677786',
    projectId: 'e-commers-app-38034',
    storageBucket: 'e-commers-app-38034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XTljQtYk5Z3kZG0hAEwAO8L4qK62lvk',
    appId: '1:175859677786:ios:220f5026c4c32597feb663',
    messagingSenderId: '175859677786',
    projectId: 'e-commers-app-38034',
    storageBucket: 'e-commers-app-38034.firebasestorage.app',
    iosBundleId: 'com.example.greenoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6XTljQtYk5Z3kZG0hAEwAO8L4qK62lvk',
    appId: '1:175859677786:ios:220f5026c4c32597feb663',
    messagingSenderId: '175859677786',
    projectId: 'e-commers-app-38034',
    storageBucket: 'e-commers-app-38034.firebasestorage.app',
    iosBundleId: 'com.example.greenoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfGg1liqvsfT33cUxxTXyXBH4Npm3UWMY',
    appId: '1:175859677786:web:b402f2326922117ffeb663',
    messagingSenderId: '175859677786',
    projectId: 'e-commers-app-38034',
    authDomain: 'e-commers-app-38034.firebaseapp.com',
    storageBucket: 'e-commers-app-38034.firebasestorage.app',
  );
}
